# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvrruoaKAaReUJlmDEwUXkM14ZhI_MaX
"""

import pandas as pd
import numpy as np
import joblib
import streamlit as st
import pickle
import warnings
warnings.filterwarnings('ignore')

model=pickle.load(open('lr_pipeline.pkl','rb'))

import streamlit as st
import joblib

# Page Configuration
st.set_page_config(
    page_title="Sentiment Analyzer",
    page_icon="📝",
    layout="centered"
)

# Custom CSS for styling
st.markdown("""
    <style>
        .main {
            background-color: #f9f9f9;
            padding: 2rem;
            border-radius: 10px;
        }
        h1 {
            color: #4a4a4a;
        }
        .stTextArea textarea {
            font-size: 16px;
        }
        .footer {
            text-align: center;
            color: gray;
            font-size: 13px;
            margin-top: 2rem;
        }
    </style>
""", unsafe_allow_html=True)

# Main Content
st.markdown('<div class="main">', unsafe_allow_html=True)

st.markdown("## 🧠 Review Sentiment Analyzer")
st.markdown("Enter your review below and let AI detect whether the sentiment is **Positive**, **Negative**, or **Neutral**!")

# Load the model
try:
    model = joblib.load("lr_pipeline.pkl")
    st.success("✅ Model loaded successfully!")
except Exception as e:
    st.error(f"❌ Failed to load model: {e}")
    st.stop()

# User input
st.markdown("### ✍️ Your Review")
user_input = st.text_area("Type your review here:", height=150, placeholder="e.g., The product quality was amazing!")

# Prediction
# Only show output after user types something
if user_input:
    input_data = np.array([user_input])

    # Prediction
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]


    st.markdown("### 🔍 Result")

    if prediction == 'positive':
        st.success("😊 Sentiment: **Positive**")
    elif prediction == 'negative':
        st.error("🙁 Sentiment: **Negative**")
    else:
        st.warning("😐 Sentiment: **Neutral**")

    st.markdown("#### 🗒️ Your Original Review")
    st.info(user_input)
else:
    st.info("🕵️ Please enter a review above to analyze sentiment.")

st.markdown("</div>", unsafe_allow_html=True)

# Footer
st.markdown('<div class="footer">Made with ❤️ using Streamlit | SVM + TF-IDF Pipeline</div>', unsafe_allow_html=True)

